### ISSUE TITLE
[autorecorder] Change demo folder

### ISSUE THREAD

**Issue by lunatixxx** [shqke/sp_public#2]
Is is possible ?

**Comment by shqke** [comment]
By default it records into mod folder.

You need to prepend path to value of `sm_autorecord_pathfmt`, e.g. `replays/%Y%m%d/auto-%H%M%S-%l-%q` (will be something like `replays/20200101/auto-234820-c8m1_apartment-4321.dem`).

**Comment by lunatixxx** [comment]
Did that and it is still recording in the main folder.

**Comment by shqke** [comment]
Perhaps you have `tv_autorecord` set to `1`? If you unset it, plugin will take control over automated recording.
