### ISSUE TITLE
[hltvcameras] Compilation issue

### ISSUE THREAD

**Issue by KadabraZz** [shqke/sp_public#5]
I can't compile, I think something is missing about #include <@shqke/util/files>

**Comment by shqke** [comment]
Same as #6, you can get include files from [artifact](https://github.com/shqke/sp_public/actions/workflows/main.yml), or to copy contents of [dep include folder](https://github.com/shqke/sp_public/tree/master/.deps/include) into your `sourcemod/include/` destination.

**Comment by KadabraZz** [comment]
I'm sorry I didn't realize that, I'm an idiot, thank you.
