### ISSUE TITLE
[autorecorder] Compilation issue

### ISSUE THREAD

**Issue by KadabraZz** [shqke/sp_public#6]
I can't compile, I think something is missing fatal error 183: cannot read from file: "sourcetvmanager"

**Comment by shqke** [comment]
You can get include files from [artifact](https://github.com/shqke/sp_public/actions/workflows/main.yml), or get a missing include from [extension](https://github.com/peace-maker/sourcetvmanager) noted in [README.md](https://github.com/shqke/sp_public/blob/master/autorecorder/README.md).
