### ISSUE TITLE
[Autorecorder] Unable to start recording

### ISSUE THREAD

**Issue by Skeletor** [shqke/sp_public#9]
I've tried starting a recording with both console commands "sm_record" and/or using the sourcemod function ServerCommand(). sm_autorecord_pathfmt is set to "%f/demos/auto-%Y%m%d-%H%M%S-%l-%q".

However I'm getting the following error:

Unable to start recording (error: "Failed to start a recording (path: "left4dead/demos/auto-20231106-191950-l4d_vs_hospital05_rooftop-82029.dem")")
L 11/06/2023 - 19:19:50: [autorecorder.smx] Unable to start recording (by: Console<0><Console><Console>, error: "Failed to start a recording (path: "left4dead/demos/auto-20231106-191950-l4d_vs_hospital05_rooftop-82029.dem")")

**Comment by shqke** [comment]
If you're on a linux, then make sure your game process has a write permission to write into a path thats generated using your `pathfmt` setting. Having (rwxr-x--x/0751, umask 022) on your mod folder should be enough.

See utils: [chown](https://man7.org/linux/man-pages/man1/chown.1.html), [chmod](https://man7.org/linux/man-pages/man1/chmod.1.html), [umask](https://man7.org/linux/man-pages/man1/umask.1p.html).

**Comment by Skeletor** [comment]
Yep that did the trick

**Comment by cy115** [comment]
> If you're on a linux, then make sure your game process has a write permission to write into a path thats generated using your setting. Having (rwxr-x--x/0751, umask 022) on your mod folder should be enough.`pathfmt`
> 
> See utils: [chown](https://man7.org/linux/man-pages/man1/chown.1.html), [chmod](https://man7.org/linux/man-pages/man1/chmod.1.html), [umask](https://man7.org/linux/man-pages/man1/umask.1p.html).

idk what game process means, does it means srcds_run or srcds_linux? And What should i need to do to the folders

**Comment by shqke** [comment]
Game process as in user under which it is ran, - said user should have permissions to write into a specified folder.

You could recursively change ownership (chown) to a specific user, then set permissions (chmod, also recursively) to a mod folder. Refer to respective manual page for each command usage.
